//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HabitatReStoreMobile.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VolunteerInfo", Namespace="http://schemas.datacontract.org/2004/07/HabitatWCFService")]
    public partial class VolunteerInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AddressField;
        
        private string Address2Field;
        
        private string CityField;
        
        private System.DateTime DOBField;
        
        private string EmailField;
        
        private string First_NameField;
        
        private char GenderField;
        
        private string Last_NameField;
        
        private string Middle_NameField;
        
        private string PhoneField;
        
        private string SSNField;
        
        private string StateField;
        
        private int Status_Map_IDField;
        
        private int Volunteer_IDField;
        
        private string ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((this.DOBField.Equals(value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First_Name {
            get {
                return this.First_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_NameField, value) != true)) {
                    this.First_NameField = value;
                    this.RaisePropertyChanged("First_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Last_Name {
            get {
                return this.Last_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Last_NameField, value) != true)) {
                    this.Last_NameField = value;
                    this.RaisePropertyChanged("Last_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Middle_Name {
            get {
                return this.Middle_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Middle_NameField, value) != true)) {
                    this.Middle_NameField = value;
                    this.RaisePropertyChanged("Middle_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SSN {
            get {
                return this.SSNField;
            }
            set {
                if ((object.ReferenceEquals(this.SSNField, value) != true)) {
                    this.SSNField = value;
                    this.RaisePropertyChanged("SSN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status_Map_ID {
            get {
                return this.Status_Map_IDField;
            }
            set {
                if ((this.Status_Map_IDField.Equals(value) != true)) {
                    this.Status_Map_IDField = value;
                    this.RaisePropertyChanged("Status_Map_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Volunteer_ID {
            get {
                return this.Volunteer_IDField;
            }
            set {
                if ((this.Volunteer_IDField.Equals(value) != true)) {
                    this.Volunteer_IDField = value;
                    this.RaisePropertyChanged("Volunteer_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DonorInfo", Namespace="http://schemas.datacontract.org/2004/07/HabitatWCFService")]
    public partial class DonorInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AddressField;
        
        private string Address2Field;
        
        private string CityField;
        
        private int Donor_IDField;
        
        private string EmailField;
        
        private string First_NameField;
        
        private char GenderField;
        
        private string Last_NameField;
        
        private string Middle_NameField;
        
        private string PhoneField;
        
        private string StateField;
        
        private int Status_Map_IDField;
        
        private string ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Donor_ID {
            get {
                return this.Donor_IDField;
            }
            set {
                if ((this.Donor_IDField.Equals(value) != true)) {
                    this.Donor_IDField = value;
                    this.RaisePropertyChanged("Donor_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First_Name {
            get {
                return this.First_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_NameField, value) != true)) {
                    this.First_NameField = value;
                    this.RaisePropertyChanged("First_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Last_Name {
            get {
                return this.Last_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Last_NameField, value) != true)) {
                    this.Last_NameField = value;
                    this.RaisePropertyChanged("Last_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Middle_Name {
            get {
                return this.Middle_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Middle_NameField, value) != true)) {
                    this.Middle_NameField = value;
                    this.RaisePropertyChanged("Middle_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status_Map_ID {
            get {
                return this.Status_Map_IDField;
            }
            set {
                if ((this.Status_Map_IDField.Equals(value) != true)) {
                    this.Status_Map_IDField = value;
                    this.RaisePropertyChanged("Status_Map_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DonationInfo", Namespace="http://schemas.datacontract.org/2004/07/HabitatWCFService")]
    public partial class DonationInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AddressField;
        
        private string Address2Field;
        
        private bool Bypass_FlagField;
        
        private string CityField;
        
        private int Donor_IDField;
        
        private string StateField;
        
        private int Status_Map_IDField;
        
        private int Store_IDField;
        
        private string ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Bypass_Flag {
            get {
                return this.Bypass_FlagField;
            }
            set {
                if ((this.Bypass_FlagField.Equals(value) != true)) {
                    this.Bypass_FlagField = value;
                    this.RaisePropertyChanged("Bypass_Flag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Donor_ID {
            get {
                return this.Donor_IDField;
            }
            set {
                if ((this.Donor_IDField.Equals(value) != true)) {
                    this.Donor_IDField = value;
                    this.RaisePropertyChanged("Donor_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status_Map_ID {
            get {
                return this.Status_Map_IDField;
            }
            set {
                if ((this.Status_Map_IDField.Equals(value) != true)) {
                    this.Status_Map_IDField = value;
                    this.RaisePropertyChanged("Status_Map_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Store_ID {
            get {
                return this.Store_IDField;
            }
            set {
                if ((this.Store_IDField.Equals(value) != true)) {
                    this.Store_IDField = value;
                    this.RaisePropertyChanged("Store_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemInfo", Namespace="http://schemas.datacontract.org/2004/07/HabitatWCFService")]
    public partial class ItemInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int Donation_IDField;
        
        private byte[] Donation_ImageField;
        
        private int Item_Category_IDField;
        
        private int Item_IDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Donation_ID {
            get {
                return this.Donation_IDField;
            }
            set {
                if ((this.Donation_IDField.Equals(value) != true)) {
                    this.Donation_IDField = value;
                    this.RaisePropertyChanged("Donation_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Donation_Image {
            get {
                return this.Donation_ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.Donation_ImageField, value) != true)) {
                    this.Donation_ImageField = value;
                    this.RaisePropertyChanged("Donation_Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Item_Category_ID {
            get {
                return this.Item_Category_IDField;
            }
            set {
                if ((this.Item_Category_IDField.Equals(value) != true)) {
                    this.Item_Category_IDField = value;
                    this.RaisePropertyChanged("Item_Category_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Item_ID {
            get {
                return this.Item_IDField;
            }
            set {
                if ((this.Item_IDField.Equals(value) != true)) {
                    this.Item_IDField = value;
                    this.RaisePropertyChanged("Item_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemCategory", Namespace="http://schemas.datacontract.org/2004/07/HabitatWCFService")]
    public partial class ItemCategory : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DescriptionField;
        
        private int Item_Category_IDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Item_Category_ID {
            get {
                return this.Item_Category_IDField;
            }
            set {
                if ((this.Item_Category_IDField.Equals(value) != true)) {
                    this.Item_Category_IDField = value;
                    this.RaisePropertyChanged("Item_Category_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IHabitatService")]
    public interface IHabitatService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IHabitatService/InsertVolunteer", ReplyAction="http://tempuri.org/IHabitatService/InsertVolunteerResponse")]
        System.IAsyncResult BeginInsertVolunteer(HabitatReStoreMobile.ServiceReference1.VolunteerInfo volunteerInfo, System.AsyncCallback callback, object asyncState);
        
        int EndInsertVolunteer(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IHabitatService/InsertDonor", ReplyAction="http://tempuri.org/IHabitatService/InsertDonorResponse")]
        System.IAsyncResult BeginInsertDonor(HabitatReStoreMobile.ServiceReference1.DonorInfo donorInfo, System.AsyncCallback callback, object asyncState);
        
        int EndInsertDonor(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IHabitatService/InsertDonation", ReplyAction="http://tempuri.org/IHabitatService/InsertDonationResponse")]
        System.IAsyncResult BeginInsertDonation(HabitatReStoreMobile.ServiceReference1.DonationInfo donationInfo, HabitatReStoreMobile.ServiceReference1.ItemInfo itemInfo, System.AsyncCallback callback, object asyncState);
        
        int EndInsertDonation(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IHabitatService/GetDonorFromEmail", ReplyAction="http://tempuri.org/IHabitatService/GetDonorFromEmailResponse")]
        System.IAsyncResult BeginGetDonorFromEmail(string email, System.AsyncCallback callback, object asyncState);
        
        HabitatReStoreMobile.ServiceReference1.DonorInfo EndGetDonorFromEmail(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IHabitatService/GetItemCategories", ReplyAction="http://tempuri.org/IHabitatService/GetItemCategoriesResponse")]
        System.IAsyncResult BeginGetItemCategories(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<HabitatReStoreMobile.ServiceReference1.ItemCategory> EndGetItemCategories(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHabitatServiceChannel : HabitatReStoreMobile.ServiceReference1.IHabitatService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsertVolunteerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InsertVolunteerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsertDonorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InsertDonorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsertDonationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InsertDonationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDonorFromEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDonorFromEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HabitatReStoreMobile.ServiceReference1.DonorInfo Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HabitatReStoreMobile.ServiceReference1.DonorInfo)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetItemCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetItemCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<HabitatReStoreMobile.ServiceReference1.ItemCategory> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<HabitatReStoreMobile.ServiceReference1.ItemCategory>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HabitatServiceClient : System.ServiceModel.ClientBase<HabitatReStoreMobile.ServiceReference1.IHabitatService>, HabitatReStoreMobile.ServiceReference1.IHabitatService {
        
        private BeginOperationDelegate onBeginInsertVolunteerDelegate;
        
        private EndOperationDelegate onEndInsertVolunteerDelegate;
        
        private System.Threading.SendOrPostCallback onInsertVolunteerCompletedDelegate;
        
        private BeginOperationDelegate onBeginInsertDonorDelegate;
        
        private EndOperationDelegate onEndInsertDonorDelegate;
        
        private System.Threading.SendOrPostCallback onInsertDonorCompletedDelegate;
        
        private BeginOperationDelegate onBeginInsertDonationDelegate;
        
        private EndOperationDelegate onEndInsertDonationDelegate;
        
        private System.Threading.SendOrPostCallback onInsertDonationCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDonorFromEmailDelegate;
        
        private EndOperationDelegate onEndGetDonorFromEmailDelegate;
        
        private System.Threading.SendOrPostCallback onGetDonorFromEmailCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetItemCategoriesDelegate;
        
        private EndOperationDelegate onEndGetItemCategoriesDelegate;
        
        private System.Threading.SendOrPostCallback onGetItemCategoriesCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public HabitatServiceClient() : 
                base(HabitatServiceClient.GetDefaultBinding(), HabitatServiceClient.GetDefaultEndpointAddress()) {
        }
        
        public HabitatServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(HabitatServiceClient.GetBindingForEndpoint(endpointConfiguration), HabitatServiceClient.GetEndpointAddress(endpointConfiguration)) {
        }
        
        public HabitatServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HabitatServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
        }
        
        public HabitatServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HabitatServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
        }
        
        public HabitatServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<InsertVolunteerCompletedEventArgs> InsertVolunteerCompleted;
        
        public event System.EventHandler<InsertDonorCompletedEventArgs> InsertDonorCompleted;
        
        public event System.EventHandler<InsertDonationCompletedEventArgs> InsertDonationCompleted;
        
        public event System.EventHandler<GetDonorFromEmailCompletedEventArgs> GetDonorFromEmailCompleted;
        
        public event System.EventHandler<GetItemCategoriesCompletedEventArgs> GetItemCategoriesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HabitatReStoreMobile.ServiceReference1.IHabitatService.BeginInsertVolunteer(HabitatReStoreMobile.ServiceReference1.VolunteerInfo volunteerInfo, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsertVolunteer(volunteerInfo, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int HabitatReStoreMobile.ServiceReference1.IHabitatService.EndInsertVolunteer(System.IAsyncResult result) {
            return base.Channel.EndInsertVolunteer(result);
        }
        
        private System.IAsyncResult OnBeginInsertVolunteer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            HabitatReStoreMobile.ServiceReference1.VolunteerInfo volunteerInfo = ((HabitatReStoreMobile.ServiceReference1.VolunteerInfo)(inValues[0]));
            return ((HabitatReStoreMobile.ServiceReference1.IHabitatService)(this)).BeginInsertVolunteer(volunteerInfo, callback, asyncState);
        }
        
        private object[] OnEndInsertVolunteer(System.IAsyncResult result) {
            int retVal = ((HabitatReStoreMobile.ServiceReference1.IHabitatService)(this)).EndInsertVolunteer(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInsertVolunteerCompleted(object state) {
            if ((this.InsertVolunteerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertVolunteerCompleted(this, new InsertVolunteerCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsertVolunteerAsync(HabitatReStoreMobile.ServiceReference1.VolunteerInfo volunteerInfo) {
            this.InsertVolunteerAsync(volunteerInfo, null);
        }
        
        public void InsertVolunteerAsync(HabitatReStoreMobile.ServiceReference1.VolunteerInfo volunteerInfo, object userState) {
            if ((this.onBeginInsertVolunteerDelegate == null)) {
                this.onBeginInsertVolunteerDelegate = new BeginOperationDelegate(this.OnBeginInsertVolunteer);
            }
            if ((this.onEndInsertVolunteerDelegate == null)) {
                this.onEndInsertVolunteerDelegate = new EndOperationDelegate(this.OnEndInsertVolunteer);
            }
            if ((this.onInsertVolunteerCompletedDelegate == null)) {
                this.onInsertVolunteerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertVolunteerCompleted);
            }
            base.InvokeAsync(this.onBeginInsertVolunteerDelegate, new object[] {
                        volunteerInfo}, this.onEndInsertVolunteerDelegate, this.onInsertVolunteerCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HabitatReStoreMobile.ServiceReference1.IHabitatService.BeginInsertDonor(HabitatReStoreMobile.ServiceReference1.DonorInfo donorInfo, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsertDonor(donorInfo, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int HabitatReStoreMobile.ServiceReference1.IHabitatService.EndInsertDonor(System.IAsyncResult result) {
            return base.Channel.EndInsertDonor(result);
        }
        
        private System.IAsyncResult OnBeginInsertDonor(object[] inValues, System.AsyncCallback callback, object asyncState) {
            HabitatReStoreMobile.ServiceReference1.DonorInfo donorInfo = ((HabitatReStoreMobile.ServiceReference1.DonorInfo)(inValues[0]));
            return ((HabitatReStoreMobile.ServiceReference1.IHabitatService)(this)).BeginInsertDonor(donorInfo, callback, asyncState);
        }
        
        private object[] OnEndInsertDonor(System.IAsyncResult result) {
            int retVal = ((HabitatReStoreMobile.ServiceReference1.IHabitatService)(this)).EndInsertDonor(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInsertDonorCompleted(object state) {
            if ((this.InsertDonorCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertDonorCompleted(this, new InsertDonorCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsertDonorAsync(HabitatReStoreMobile.ServiceReference1.DonorInfo donorInfo) {
            this.InsertDonorAsync(donorInfo, null);
        }
        
        public void InsertDonorAsync(HabitatReStoreMobile.ServiceReference1.DonorInfo donorInfo, object userState) {
            if ((this.onBeginInsertDonorDelegate == null)) {
                this.onBeginInsertDonorDelegate = new BeginOperationDelegate(this.OnBeginInsertDonor);
            }
            if ((this.onEndInsertDonorDelegate == null)) {
                this.onEndInsertDonorDelegate = new EndOperationDelegate(this.OnEndInsertDonor);
            }
            if ((this.onInsertDonorCompletedDelegate == null)) {
                this.onInsertDonorCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertDonorCompleted);
            }
            base.InvokeAsync(this.onBeginInsertDonorDelegate, new object[] {
                        donorInfo}, this.onEndInsertDonorDelegate, this.onInsertDonorCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HabitatReStoreMobile.ServiceReference1.IHabitatService.BeginInsertDonation(HabitatReStoreMobile.ServiceReference1.DonationInfo donationInfo, HabitatReStoreMobile.ServiceReference1.ItemInfo itemInfo, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsertDonation(donationInfo, itemInfo, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int HabitatReStoreMobile.ServiceReference1.IHabitatService.EndInsertDonation(System.IAsyncResult result) {
            return base.Channel.EndInsertDonation(result);
        }
        
        private System.IAsyncResult OnBeginInsertDonation(object[] inValues, System.AsyncCallback callback, object asyncState) {
            HabitatReStoreMobile.ServiceReference1.DonationInfo donationInfo = ((HabitatReStoreMobile.ServiceReference1.DonationInfo)(inValues[0]));
            HabitatReStoreMobile.ServiceReference1.ItemInfo itemInfo = ((HabitatReStoreMobile.ServiceReference1.ItemInfo)(inValues[1]));
            return ((HabitatReStoreMobile.ServiceReference1.IHabitatService)(this)).BeginInsertDonation(donationInfo, itemInfo, callback, asyncState);
        }
        
        private object[] OnEndInsertDonation(System.IAsyncResult result) {
            int retVal = ((HabitatReStoreMobile.ServiceReference1.IHabitatService)(this)).EndInsertDonation(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInsertDonationCompleted(object state) {
            if ((this.InsertDonationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertDonationCompleted(this, new InsertDonationCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsertDonationAsync(HabitatReStoreMobile.ServiceReference1.DonationInfo donationInfo, HabitatReStoreMobile.ServiceReference1.ItemInfo itemInfo) {
            this.InsertDonationAsync(donationInfo, itemInfo, null);
        }
        
        public void InsertDonationAsync(HabitatReStoreMobile.ServiceReference1.DonationInfo donationInfo, HabitatReStoreMobile.ServiceReference1.ItemInfo itemInfo, object userState) {
            if ((this.onBeginInsertDonationDelegate == null)) {
                this.onBeginInsertDonationDelegate = new BeginOperationDelegate(this.OnBeginInsertDonation);
            }
            if ((this.onEndInsertDonationDelegate == null)) {
                this.onEndInsertDonationDelegate = new EndOperationDelegate(this.OnEndInsertDonation);
            }
            if ((this.onInsertDonationCompletedDelegate == null)) {
                this.onInsertDonationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertDonationCompleted);
            }
            base.InvokeAsync(this.onBeginInsertDonationDelegate, new object[] {
                        donationInfo,
                        itemInfo}, this.onEndInsertDonationDelegate, this.onInsertDonationCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HabitatReStoreMobile.ServiceReference1.IHabitatService.BeginGetDonorFromEmail(string email, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDonorFromEmail(email, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HabitatReStoreMobile.ServiceReference1.DonorInfo HabitatReStoreMobile.ServiceReference1.IHabitatService.EndGetDonorFromEmail(System.IAsyncResult result) {
            return base.Channel.EndGetDonorFromEmail(result);
        }
        
        private System.IAsyncResult OnBeginGetDonorFromEmail(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string email = ((string)(inValues[0]));
            return ((HabitatReStoreMobile.ServiceReference1.IHabitatService)(this)).BeginGetDonorFromEmail(email, callback, asyncState);
        }
        
        private object[] OnEndGetDonorFromEmail(System.IAsyncResult result) {
            HabitatReStoreMobile.ServiceReference1.DonorInfo retVal = ((HabitatReStoreMobile.ServiceReference1.IHabitatService)(this)).EndGetDonorFromEmail(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDonorFromEmailCompleted(object state) {
            if ((this.GetDonorFromEmailCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDonorFromEmailCompleted(this, new GetDonorFromEmailCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDonorFromEmailAsync(string email) {
            this.GetDonorFromEmailAsync(email, null);
        }
        
        public void GetDonorFromEmailAsync(string email, object userState) {
            if ((this.onBeginGetDonorFromEmailDelegate == null)) {
                this.onBeginGetDonorFromEmailDelegate = new BeginOperationDelegate(this.OnBeginGetDonorFromEmail);
            }
            if ((this.onEndGetDonorFromEmailDelegate == null)) {
                this.onEndGetDonorFromEmailDelegate = new EndOperationDelegate(this.OnEndGetDonorFromEmail);
            }
            if ((this.onGetDonorFromEmailCompletedDelegate == null)) {
                this.onGetDonorFromEmailCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDonorFromEmailCompleted);
            }
            base.InvokeAsync(this.onBeginGetDonorFromEmailDelegate, new object[] {
                        email}, this.onEndGetDonorFromEmailDelegate, this.onGetDonorFromEmailCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult HabitatReStoreMobile.ServiceReference1.IHabitatService.BeginGetItemCategories(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetItemCategories(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<HabitatReStoreMobile.ServiceReference1.ItemCategory> HabitatReStoreMobile.ServiceReference1.IHabitatService.EndGetItemCategories(System.IAsyncResult result) {
            return base.Channel.EndGetItemCategories(result);
        }
        
        private System.IAsyncResult OnBeginGetItemCategories(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((HabitatReStoreMobile.ServiceReference1.IHabitatService)(this)).BeginGetItemCategories(callback, asyncState);
        }
        
        private object[] OnEndGetItemCategories(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<HabitatReStoreMobile.ServiceReference1.ItemCategory> retVal = ((HabitatReStoreMobile.ServiceReference1.IHabitatService)(this)).EndGetItemCategories(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetItemCategoriesCompleted(object state) {
            if ((this.GetItemCategoriesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetItemCategoriesCompleted(this, new GetItemCategoriesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetItemCategoriesAsync() {
            this.GetItemCategoriesAsync(null);
        }
        
        public void GetItemCategoriesAsync(object userState) {
            if ((this.onBeginGetItemCategoriesDelegate == null)) {
                this.onBeginGetItemCategoriesDelegate = new BeginOperationDelegate(this.OnBeginGetItemCategories);
            }
            if ((this.onEndGetItemCategoriesDelegate == null)) {
                this.onEndGetItemCategoriesDelegate = new EndOperationDelegate(this.OnEndGetItemCategories);
            }
            if ((this.onGetItemCategoriesCompletedDelegate == null)) {
                this.onGetItemCategoriesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetItemCategoriesCompleted);
            }
            base.InvokeAsync(this.onBeginGetItemCategoriesDelegate, null, this.onEndGetItemCategoriesDelegate, this.onGetItemCategoriesCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override HabitatReStoreMobile.ServiceReference1.IHabitatService CreateChannel() {
            return new HabitatServiceClientChannel(this);
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IHabitatService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IHabitatService)) {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.5/HabitatWCFService/HabitatService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return HabitatServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IHabitatService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return HabitatServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IHabitatService);
        }
        
        private class HabitatServiceClientChannel : ChannelBase<HabitatReStoreMobile.ServiceReference1.IHabitatService>, HabitatReStoreMobile.ServiceReference1.IHabitatService {
            
            public HabitatServiceClientChannel(System.ServiceModel.ClientBase<HabitatReStoreMobile.ServiceReference1.IHabitatService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginInsertVolunteer(HabitatReStoreMobile.ServiceReference1.VolunteerInfo volunteerInfo, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = volunteerInfo;
                System.IAsyncResult _result = base.BeginInvoke("InsertVolunteer", _args, callback, asyncState);
                return _result;
            }
            
            public int EndInsertVolunteer(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("InsertVolunteer", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginInsertDonor(HabitatReStoreMobile.ServiceReference1.DonorInfo donorInfo, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = donorInfo;
                System.IAsyncResult _result = base.BeginInvoke("InsertDonor", _args, callback, asyncState);
                return _result;
            }
            
            public int EndInsertDonor(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("InsertDonor", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginInsertDonation(HabitatReStoreMobile.ServiceReference1.DonationInfo donationInfo, HabitatReStoreMobile.ServiceReference1.ItemInfo itemInfo, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = donationInfo;
                _args[1] = itemInfo;
                System.IAsyncResult _result = base.BeginInvoke("InsertDonation", _args, callback, asyncState);
                return _result;
            }
            
            public int EndInsertDonation(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("InsertDonation", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetDonorFromEmail(string email, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = email;
                System.IAsyncResult _result = base.BeginInvoke("GetDonorFromEmail", _args, callback, asyncState);
                return _result;
            }
            
            public HabitatReStoreMobile.ServiceReference1.DonorInfo EndGetDonorFromEmail(System.IAsyncResult result) {
                object[] _args = new object[0];
                HabitatReStoreMobile.ServiceReference1.DonorInfo _result = ((HabitatReStoreMobile.ServiceReference1.DonorInfo)(base.EndInvoke("GetDonorFromEmail", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetItemCategories(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetItemCategories", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<HabitatReStoreMobile.ServiceReference1.ItemCategory> EndGetItemCategories(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<HabitatReStoreMobile.ServiceReference1.ItemCategory> _result = ((System.Collections.ObjectModel.ObservableCollection<HabitatReStoreMobile.ServiceReference1.ItemCategory>)(base.EndInvoke("GetItemCategories", _args, result)));
                return _result;
            }
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IHabitatService,
        }
    }
}
